apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-app
  labels:
    stage: DEV

spec:
  selector: 
    matchLabels:
      stage: DEV
  
  repliacs: 3
  template:
    metadata:
      labels:
        stage: DEV
    spec:  
     containers:
        - name: c1
          image: esraaelhasanen/weather-app:v20250613234957
          ports:
           - containerPort: 5000
           
      
      
