apiVersion: v1
kind: Service
metadata:
  name: weather-app-service
spec:
  selector:
    stage: DEV
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30008
  type: NodePort