name: Flask CI/CD pipeline

on:
  push:
    branches:
      - main
    paths:
      - '**/*'

jobs:
  
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Install python
        uses: actions/setup-python@v2
        with:
         python-version: '3.9'
      
      - name: Install Docker
        uses: docker/setup-buildx-action@v2
      
      - name: Install dependcies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: login to dockerhub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Create Tag for docker image
        id: version
        run: |
          VERSION=v$(date +"%Y%m%d%H%M%S") 
          echo "VERSION=$VERSION" >> $GITHUB_ENV
      
      - name: Build Docker image
        run: |
          docker build . -t esraaelhasanen/weather-app:${{ env.VERSION }}
          docker image ls
      
      - name: Push to dockerhub
        run: |
          docker push esraaelhasanen/weather-app:${{ env.VERSION }}
      
      - name: Update Manifest
        run: |

          sed -i "s|image: esraaelhasanen/weather-app:.*|image: esraaelhasanen/weather-app:${{ env.VERSION }}|g" deploy/deploy.yaml
          cat deploy/deploy.yaml
      
      - name: update image on repo 
        run: |
          git config --global user.email "<>"
          git config --global user.name "GitHub Actions Bot"
          git add deploy/deploy.yaml

          git commit -m "Update deploy.yaml with new image version - ${{ env.VERSION }}"
          git remote set-url origin https://github-actions:${{ secrets.GITHUB_TOKEN }}@github.com/esraasoror22/Weather-app.git
          git push origin main



        
      

          
        
          
    
